name = "Acoustics"
uuid = "3b3a8e8f-5643-43ea-bf99-15dd952b2929"
authors = ["Mark C. Anderson <anderson.mark.az@gmail.com>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
